language: python
sudo: false
addons:
  apt:
    packages:
      - python3-scipy
      - python3-numpy
      - python-sklearn
# Whitelisting master
branches:
  only:
    - master
git:
  depth: 10
python:
  - "3.5"
before_install:
  - echo "before_install"
  - echo $VIRTUAL_ENV
  - df -h
  - date
  - pwd
  - uname -m
  - python -V
  - which python2
  - which python3
  - git --version
  - git tag
  - pip install pytest-cov pylint unidecode
  - apt-cache show python3-numpy python3-scipy
install:
  - echo "install start"
# - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
# - bash miniconda.sh -b -p ${HOME}/miniconda
# - export PATH="$HOME/miniconda/bin:$PATH"
# - conda config --set always_yes yes --set changeps1 no
# - conda update -q conda
# - conda info -a
# - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib seaborn pytest pytest-cov
# - source activate test-environment
before_script:
  - echo "before_script"
script:
  - PYTHONPATH=assignment1 python -m py.test --cov=assignment1 --cov-report term assignment1/tests/ -s --durations=10
##PYTHONPATH=assignment1 py.test --cov=assignment1 --cov-report term assignment1/tests/ -s --durations=10